package se.yrgo.dataaccess;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;

import org.springframework.stereotype.Repository;
import se.yrgo.domain.Call;
import se.yrgo.domain.Customer;

@Repository
public class CustomerDaoJdbcTemplateImpl implements CustomerDao {
    private static final String DELETE_SQL = "DELETE FROM CUSTOMER WHERE CUSTOMER_ID=?";
    private static final String UPDATE_SQL = "UPDATE CUSTOMER SET COMPANY_NAME=?, EMAIL=?, TELEPHONE=?, NOTES=? WHERE CUSTOMER_ID=?";
    private static final String INSERT_SQL = "INSERT INTO CUSTOMER (CUSTOMER_ID, COMPANY_NAME, EMAIL, TELEPHONE, NOTES) VALUES (?,?,?,?,?)";
    private static final String GET_ID_SQL = "SELECT * FROM CUSTOMER WHERE CUSTOMER_ID=?";
    private static final String GET_NAME = "SELECT * FROM CUSTOMER WHERE COMPANY_NAME=?";
    private static final String GET_ALL_SQL = "SELECT * FROM CUSTOMER";
    private static final String INSERT_CALL_SQL = "INSERT INTO CALLS (CUSTOMER_ID, TIME_AND_DATE, NOTES) VALUES (?,?,?)";
    private static final String GET_CALLS_SQL = "SELECT * FROM CALLS WHERE CUSTOMER_ID=?";

    private JdbcTemplate template;

    public CustomerDaoJdbcTemplateImpl(JdbcTemplate template) {
        this.template = template;
        createTables();
    }

    public void create(Customer newCustomer) {
        template.update(INSERT_SQL, newCustomer.getCustomerId(), newCustomer.getCompanyName(), newCustomer.getEmail(),
                newCustomer.getTelephone(), newCustomer.getNotes());
    }

    private void createTables() {
        try {
            // CUSTOMER table
            this.template.update(
                    "CREATE TABLE CUSTOMER (" +
                            "CUSTOMER_ID VARCHAR(20) PRIMARY KEY, " +
                            "COMPANY_NAME VARCHAR(100), " +
                            "EMAIL VARCHAR(50), " +
                            "TELEPHONE VARCHAR(15), " +
                            "NOTES VARCHAR(255))");

            // CALLS table (OBS: inte CALL)
            this.template.update(
                    "CREATE TABLE CALLS (" +
                            "CALL_ID INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1), " +
                            "CUSTOMER_ID VARCHAR(20), " +
                            "TIME_AND_DATE TIMESTAMP, " +
                            "NOTES VARCHAR(255))");

        } catch (org.springframework.jdbc.BadSqlGrammarException e) {
            System.out.println("Assuming the tables already exist");
        }
    }

    public Customer getById(String customerId) throws RecordNotFoundException {
        return this.template.queryForObject(GET_ID_SQL, new CustomerRowMapper(), customerId);
    }

    public List<Customer> getByName(String name) {
        return this.template.query(GET_NAME, new CustomerRowMapper(), name);
    }

    public void update(Customer customerToUpdate) throws RecordNotFoundException {
        this.template.update(
                UPDATE_SQL, customerToUpdate.getCompanyName(), customerToUpdate.getEmail(),
                customerToUpdate.getTelephone(), customerToUpdate.getNotes(), customerToUpdate.getCustomerId());
    }

    public void delete(Customer oldCustomer) throws RecordNotFoundException {
        this.template.update(DELETE_SQL, oldCustomer.getCustomerId());
    }

    public List<Customer> getAllCustomers() {
        return this.template.query(GET_ALL_SQL, new CustomerRowMapper());
    }

    public Customer getFullCustomerDetail(String customerId) throws RecordNotFoundException {
        Customer customer = this.template.queryForObject(GET_ID_SQL, new CustomerRowMapper(), customerId);

        List<Call> calls = this.template.query(GET_CALLS_SQL, new CallRowMapper(), customerId);

        customer.setCalls(calls);

        return customer;
    }

    public void addCall(Call newCall, String customerId) throws RecordNotFoundException {
        this.getById(customerId);

        this.template.update(
                INSERT_CALL_SQL,
                customerId,
                new java.sql.Timestamp(newCall.getTimeAndDate().getTime()),
                newCall.getNotes());
    }
}

class CustomerRowMapper implements RowMapper<Customer> {
    public Customer mapRow(ResultSet rs, int arg1) throws SQLException {
        String customerId = rs.getString(1);
        String companyName = rs.getString(2);
        String email = rs.getString(3);
        String telephone = rs.getString(4);
        String notes = rs.getString(5);

        return new Customer(customerId, companyName, email, telephone, notes);
    }
}

class CallRowMapper implements RowMapper<Call> {
    public Call mapRow(ResultSet rs, int rowNum) throws SQLException {

        String notes = rs.getString("NOTES");
        java.util.Date date = rs.getTimestamp("TIME_AND_DATE");

        return new Call(notes, date);

    }
}
